function sm_car_config_logging(modelname)
%sm_car_config_logging  Configure logging for Simscape Vehicle Templates Model
%   sm_car_config_logging(modelname)
%   This function configures the logging for the Simscape Vehicle Templates Model.
%
% Copyright 2018-2025 The MathWorks, Inc.

ph = get_param([modelname '/Driver'],'PortHandles');
set_param(ph.Outport(1),...
    'DataLogging','on',...
    'DataLoggingNameMode','Custom',...
    'DataLoggingName','DrvBus');

ph = get_param([modelname '/Controller'],'PortHandles');
set_param(ph.Outport(1),...
    'DataLogging','on',...
    'DataLoggingNameMode','Custom',...
    'DataLoggingName','CtrlBus');

ph = get_param([modelname '/Vehicle'],'PortHandles');
set_param(ph.Outport(1),...
    'DataLogging','on',...
    'DataLoggingNameMode','Custom',...
    'DataLoggingName','TrlBus');

set_param(ph.Outport(2),...
    'DataLogging','on',...
    'DataLoggingNameMode','Custom',...
    'DataLoggingName','VehBus');

ph = get_param([modelname '/Road'],'PortHandles');
set_param(ph.Outport(1),...
    'DataLogging','on',...
    'DataLoggingNameMode','Custom',...
    'DataLoggingName','RdBus');