function [] = crg_demo_gen_target()
% CRG_DEMO_GEN_TARGET CRG demo to generate a surface crg file.
%   CRG_DEMO_GEN_TARGET demonstrates how the target crg file can be
%   generated. It uses one of the OpenCRG data samples as measurement
%   data source.
%   In the first step, the refline.crg file has to be generated by
%   calling CRG_DEMO_GEN_REFLINE.
%   In the second step, we use the just generated refline to evaluate the
%   measurement data at the given CRG elevation grid points.
%   In this third step, the surface.crg file has to be finally processed by
%   CRG_GEN_TARGET for later use, resulting in the target.crg file.
%
%   Example:
%   crg_demo_gen_target       runs this demo to generate "target.crg"
%
%   See also CRG_INTRO.

%   Copyright 2005-2010 OpenCRG - Daimler AG - Jochen Rauh
%
%   Licensed under the Apache License, Version 2.0 (the "License");
%   you may not use this file except in compliance with the License.
%   You may obtain a copy of the License at
%
%       http://www.apache.org/licenses/LICENSE-2.0
%
%   Unless required by applicable law or agreed to in writing, software
%   distributed under the License is distributed on an "AS IS" BASIS,
%   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%   See the License for the specific language governing permissions and
%   limitations under the License.
%
%   More Information on OpenCRG open file formats and tools can be found at
%
%       http://www.opencrg.org
%
%   $Id: crg_demo_gen_target.m 216 2011-02-05 21:59:55Z jorauh $

%% set processing parameters and options

lshow = 1;  % show results [0 1]

cutrl = 3;   % cut road NaN parts at right/left side (at mean NaN limit + 3*sigma)
cutbe = 5;   % cut road NaN parts at begin/end (at mean NaN limit - 5*sigma)

bwlen = 20;   % filter window length for banking
swlen = 20;   % filter window length for slope


%% use CRG refline generated by crg_demo_gen_surface

crg = crg_read('surface.crg');

%% simplify access

il = crg.il;
ir = crg.ir;
[nu nv] = size(crg.z);

%% cut NaN areas

% right/left border to include cutrl*sigma outside of mean right/left border
jr = max(min(ir), floor(mean(ir) - cutrl*std(ir)));
jl = min(max(il),  ceil(mean(il) + cutrl*std(il)));

% begin/end border to include cutbe*sigma outside of mean begin/end border
kr = floor(mean(ir) + cutbe*std(ir));
kl =  ceil(mean(il) - cutbe*std(il));
jb = max(find(ir<=kr, 1, 'first'), find(il>=kl, 1, 'first'));
je = min(find(ir<=kr, 1, 'last' ), find(il>=kl, 1, 'last' ));

fprintf(1, 'surface.crg elevation grid size = (1:%d, 1:%d)\n', nu, nv);

if jr>1 || jl<nv || jb>1 || je<nu
    fprintf(1, 'borders with NaNs will be removed, elevation grid cut size = (%d:%d, %d:%d)\n', jb, je, kr, kl);
    crg = crg_cut_iuiv(crg, [jb je], [jr jl]);
    [nu nv] = size(crg.z);
    fprintf(1, 'target.crg  elevation grid size = (1:%d, 1:%d)\n', nu, nv);
else
    fprintf(1, 'no borders with NaNs are removed.\n');
end

%% separate slope and banking

crg = crg_separate_sb(crg, swlen, bwlen)

%% write surface CRG data set

crg.filenm = 'target.crg';
crg.ct{1}  = sprintf('demo target generated by %s at %s', mfilename, datestr(now, 31));
crg_write(crg, crg.filenm);

fprintf(1, '\nCRG target file %s is written.\n', crg.filenm);

%% show what we have got so far ...

if lshow
    crg = crg_show(crg);
    crg_wgs84_crg2html(crg, 'target.html');
    web('target.html', '-browser');
end
