function [simTime, tireFx, tireFy, tireFz, ...
    wheelAngles, wheelCamber, posVeh, psiVeh, velVeh, ...
    tirePx, tirePy, tirePz] = sm_car_plot3d_get_data(logsout)
% sm_car_plot3d_get_data  Extract data for 3D plot from simulation results
% [simTime, ...] = sm_car_plot3d_get_data(logsout)
%    This function extracts data from vehicle simulation results and
%    assigns them to variables that can be directly used with the Vehicle
%    Results 3D Plotter. The code is written to be consistent with the bus
%    structure of the Simscape Vehicle Templates, but could be adapted for
%    other sets of simulation results.
%
%    simTime      Simulation Time
%    tireFx, tireFy, tireFz   Forces at contact patch for all tires (n x 4)
%                             Longitudinal, lateral, vertical 
%    wheelAngles  Wheel toe angle    (n x 4)
%    wheelCamber  Wheel camber angle (n x 4)
%    posVeh       Vehicle x, y, z position     (n x 3)
%    psiVeh       Body roll, pitch, yaw angles (n x 3)
%    velVeh       Vehicle x, y, z velocities   (n x 3)
%    tirePx, tirePy, tirePz   Wheel center position in global x, y, z (n x 4)
%
% Copyright 2025 The MathWorks, Inc.

% Extract data from logsout
logsout_VehBus = logsout.get('VehBus');

simTime             = logsout_VehBus.Values.Chassis.WhlL1.xyz.Time;
tireFx  = [...
    squeeze(logsout_VehBus.Values.Chassis.WhlL1.Fx.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlR1.Fx.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlL2.Fx.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlR2.Fx.Data)];

tireFy  = [...
    squeeze(logsout_VehBus.Values.Chassis.WhlL1.Fy.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlR1.Fy.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlL2.Fy.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlR2.Fy.Data)];

tireFz  = [...
    squeeze(logsout_VehBus.Values.Chassis.WhlL1.Fz.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlR1.Fz.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlL2.Fz.Data) ...
    squeeze(logsout_VehBus.Values.Chassis.WhlR2.Fz.Data)];

% Tire position
tirePx =  [...
    logsout_VehBus.Values.Chassis.WhlL1.xyz.Data(:,1) ...
    logsout_VehBus.Values.Chassis.WhlR1.xyz.Data(:,1) ...
    logsout_VehBus.Values.Chassis.WhlL2.xyz.Data(:,1) ...
    logsout_VehBus.Values.Chassis.WhlR2.xyz.Data(:,1) ...
    ];

tirePy =  [...
    logsout_VehBus.Values.Chassis.WhlL1.xyz.Data(:,2) ...
    logsout_VehBus.Values.Chassis.WhlR1.xyz.Data(:,2) ...
    logsout_VehBus.Values.Chassis.WhlL2.xyz.Data(:,2) ...
    logsout_VehBus.Values.Chassis.WhlR2.xyz.Data(:,2) ...
    ];

tirePz =  [...
    logsout_VehBus.Values.Chassis.WhlL1.xyz.Data(:,3) ...
    logsout_VehBus.Values.Chassis.WhlR1.xyz.Data(:,3) ...
    logsout_VehBus.Values.Chassis.WhlL2.xyz.Data(:,3) ...
    logsout_VehBus.Values.Chassis.WhlR2.xyz.Data(:,3) ...
    ];

% Note: negative signs are because toe angle is positive if wheel rotates
% towards the centerline of the vehicle.  For plotting, positive is
% rotating counterclockwise when viewed from above.
wheelAngles = [ ...
    -squeeze(logsout_VehBus.Values.Chassis.SuspA1.WhlL.aToe.Data) ...
     squeeze(logsout_VehBus.Values.Chassis.SuspA1.WhlR.aToe.Data) ...
    -squeeze(logsout_VehBus.Values.Chassis.SuspA2.WhlL.aToe.Data) ...
     squeeze(logsout_VehBus.Values.Chassis.SuspA2.WhlR.aToe.Data)]*pi/180;

% Note: negative signs are because camber angle is positive if wheel rotates
% towards the centerline of the vehicle.  For plotting, positive is
% rotating counterclockwise when viewed from the rear.
wheelCamber = [ ...
    -squeeze(logsout_VehBus.Values.Chassis.SuspA1.WhlL.aCamber.Data) ...
     squeeze(logsout_VehBus.Values.Chassis.SuspA1.WhlR.aCamber.Data) ...
    -squeeze(logsout_VehBus.Values.Chassis.SuspA2.WhlL.aCamber.Data) ...
     squeeze(logsout_VehBus.Values.Chassis.SuspA2.WhlR.aCamber.Data)]*pi/180;

posVeh = [...
    squeeze(logsout_VehBus.Values.World.x.Data) ...
    squeeze(logsout_VehBus.Values.World.y.Data) ...
    squeeze(logsout_VehBus.Values.World.z.Data)];

psiVeh = [...
    squeeze(logsout_VehBus.Values.World.aRoll.Data) ...
    squeeze(logsout_VehBus.Values.World.aPitch.Data) ...
    squeeze(logsout_VehBus.Values.World.aYaw.Data)];

velVeh = [...
    squeeze(logsout_VehBus.Values.World.vx.Data) ...
    squeeze(logsout_VehBus.Values.World.vy.Data) ...
    squeeze(logsout_VehBus.Values.World.vz.Data)];



